### ISSUE TITLE
porechop struggling with large files

### ISSUE THREAD

**Issue by caballero** [maxplanck-ie/nanoporeReads_dataTransfer#151]
large files are causing problems with large files >100GB

refactor for processing in batches and keep only a sampled report for MultiQC

https://github.com/maxplanck-ie/nanoporeReads_dataTransfer/blob/709e4b05baee1c1e5907e315289d2c553e7ee597/src/npr/rules_dorado/05_porechop.smk#L137

**Comment by WardDeb** [comment]
Duplicate of #141
