### ISSUE TITLE
data provenance

### ISSUE THREAD

**Issue by dkoppstein** [maxplanck-ie/nanoporeReads_dataTransfer#29]
Regarding the issue of bumping guppy versions, it would also be good to provide the information about which guppy version and DNA/RNA model are used to basecall to the user. I think this information is all present in the pipeline_config.yaml file.

**Comment by WardDeb** [comment]
Good point. At the moment I'm playing around with the idea to shift to multiQC, as we can customise the header relatively easily to include this and additional information. Inclusion of pycoQC metrics seems supported already. Would need some testing though.

**Comment by WardDeb** [comment]
Versions are provided in a metadata yaml to the end user now as well.
