### ISSUE TITLE
trigger with flowcell + model

### ISSUE THREAD

**Issue by WardDeb** [maxplanck-ie/nanoporeReads_dataTransfer#33]
allow forced processing using a specific model (e.g. 5mc /...)

**Comment by thomasmanke** [comment]
modifications can now be done in [d026d08](https://github.com/maxplanck-ie/nanoporeReads_dataTransfer/commit/d026d081abd9b305dfe94d10e6ca4d2fe15ea3f1):

guppy_basecaller:
  guppy_mod: 5mc_cg

**Comment by thomasmanke** [comment]
fixed in v2.0.0
