### ISSUE TITLE
pod5 mirroring of fast5 directory

### ISSUE THREAD

**Issue by dkoppstein** [maxplanck-ie/nanoporeReads_dataTransfer#42]
Currently, the pipeline is just outputting one pod5 file. It would be nice for the pod5 directories to mirror the output of the sequencer, i.e. separated into fast5_pass, fast5_fail, and per barcode, as this is often necessary for downstream analysis and totally trivial to parse out of the combined pod5. This could be done with something like the following:

```python
outdir = "/path"

for d in ["fast5_pass", "fast5_fail"]:
    for barcode in os.listdir(d):
        indir = os.path.join(d, barcode)
        call_pod5_recursively(indir, os.path.join(outdir, indir))
```

**Comment by WardDeb** [comment]
This'd be overkill for the following reason:
the sequencer's basecalling is usually using a fast model (and even if it's HAC/super we cannot assume it's the same model as the guppy version on our node). If we adhere to this this could result in a following structure:

sequencer - fast5_pass, fast5_fail
pod5 - pod5_pass, pod5_fail (as defined by the sequencer).

basecalling would then need to be executed on both pod5 directories separately, resulting in a structure like this:

pod5_pass_fastq_pass
pod5_pass_fastq_fail
pod5_fail_fastq_pass
pod5_fail_fastq_fail

One could convert all of them to pod5, and split them up later on. Though I'd opt to keep them as is for the moment. We can revisit this when some actual use case occurs.

Feel free to reopen if I misunderstood.
