### ISSUE TITLE
simplify 2_renamed.smk

### ISSUE THREAD

**Issue by dkoppstein** [maxplanck-ie/nanoporeReads_dataTransfer#47]
As per [PR 45](https://github.com/maxplanck-ie/nanoporeReads_dataTransfer/pull/45) comments, we can take advantage of snakemake's ability to create directories automatically. There is a lot of code duplication in the big if/else statement, we can also significantly simplify this as well. I would also recommend using the built-in `shell()`function for doing things like cat or cp, as it  (should?) print to output as well when using snakemake --printshellcmds.

**Comment by thomasmanke** [comment]
fixed in v2.0.0
