### ISSUE TITLE
exec/env logging

### ISSUE THREAD

**Issue by WardDeb** [maxplanck-ie/nanoporeReads_dataTransfer#93]
keep a log to the (abs) path from where the ont executable runs from

**Comment by thomasmanke** [comment]
This is now in develop: [d026d08](https://github.com/maxplanck-ie/nanoporeReads_dataTransfer/commit/d026d081abd9b305dfe94d10e6ca4d2fe15ea3f1)

**Comment by WardDeb** [comment]
Yes, knowing where the 'ont' executable lives was the original use-case.

**Comment by thomasmanke** [comment]
now in v1.2.0
